### ISSUE TITLE
Sync master to Cargo.io

### ISSUE THREAD

**Issue by lambdaburrito** [iron/iron#330]
I noticed that the latest master, that removes all unstable features, is not in sync with Cargo.io because it won't allow me to compile 'iron', 'router' or others for rustc beta when specified as:

    [dependencies]
    iron = "*"
    router = "*"

To get around this, I tried to point to the github url. However, router depends on iron using '"*"'

**Comment by fuchsnj** [comment]
@lambdaburrito As a temporary fix, you can download the repository and use a .cargo config file to override the dependency to use the one you downloaded. See the `paths` config here: http://doc.crates.io/config.html

**Comment by reem** [comment]
Fixed.

**Comment by lambdaburrito** [comment]
This shouldn't be closed as it's not fixed for the beta. I am very concerned that you cannot even see the build issues.

**Comment by reem** [comment]
@lambdaburrito I'm sorry, you are right, I misread the original post and thought this was only about iron proper not also router. I'll reopen and see what I can do about fixing this today.

**Comment by reem** [comment]
Actually fixed!
